# Generated by Django 2.1.7 on 2019-03-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100, verbose_name='From Location')),
                ('to_location', models.CharField(max_length=100, verbose_name='To Location')),
                ('departure_time', models.DateTimeField(verbose_name='Departure time')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('no_of_seats', models.IntegerField()),
            ],
        ),
    ]
