# Generated by Django 2.1.7 on 2019-03-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='booked',
        ),
    ]
