# Generated by Django 2.1.7 on 2019-03-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='no_of_seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
