# Generated by Django 2.1.7 on 2019-04-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20190328_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
