# Generated by Django 2.1.7 on 2019-04-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_booking_reminder_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reminder_sent_at',
        ),
    ]
